export interface Data {
  storeId: string;
  storeName: string;
  city: string;
  address: string;
  ownerPhoneNumber: string;
  ownerName: string;
  createdAt: string;
  updatedAt: string;
  status: boolean;
  supplierStatus: string;
  actions?: Array<string>;
}

export const data: Array<Data> = [
  {
    storeId: "2233",
    storeName: "Holy Moly",
    city: "Jakarta",
    address: "Apart 1",
    ownerPhoneNumber: "09292929202",
    ownerName: "Reon",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: true,
    supplierStatus: "Pending",
    actions: ["Edit", "Delete"],
  },
  {
    storeId: "2234",
    storeName: "Moly Moly",
    city: "Bandung",
    address: "Apart 2",
    ownerPhoneNumber: "09292929202",
    ownerName: "Aeon",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: false,
    supplierStatus: "Done",
    actions: ["Edit", "Delete"],
  },
  {
    storeId: "2235",
    storeName: "Doly Moly",
    city: "Surabaya",
    address: "Apart 3",
    ownerPhoneNumber: "09292929202",
    ownerName: "Weon",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: false,
    supplierStatus: "Pending",
    actions: ["Edit", "Delete"],
  },
  {
    storeId: "2236",
    storeName: "Aoly Moly",
    city: "Medan",
    address: "Apart 20",
    ownerPhoneNumber: "09292929202",
    ownerName: "Qeon",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: false,
    supplierStatus: "Pending",
    actions: ["Edit", "Delete"],
  },
  {
    storeId: "1233",
    storeName: "Poly Moly",
    city: "Bali",
    address: "Apart 30",
    ownerPhoneNumber: "09292929202",
    ownerName: "Ceon",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: false,
    supplierStatus: "Pending",
    actions: ["Edit", "Delete"],
  },
  {
    storeId: "1233",
    storeName: "Poly Moly",
    city: "Bali",
    address: "Apart 30",
    ownerPhoneNumber: "09292929202",
    ownerName: "Ceon",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: false,
    supplierStatus: "Pending",
    actions: ["Edit", "Delete"],
  },
  {
    storeId: "1233",
    storeName: "Poly Moly",
    city: "Bali",
    address: "Apart 30",
    ownerPhoneNumber: "09292929202",
    ownerName: "Ceon",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: false,
    supplierStatus: "Pending",
    actions: ["Edit", "Delete"],
  },
  {
    storeId: "1233",
    storeName: "Poly Moly",
    city: "Bali",
    address: "Apart 30",
    ownerPhoneNumber: "09292929202",
    ownerName: "Ceon",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: false,
    supplierStatus: "Pending",
    actions: ["Edit", "Delete"],
  },
  {
    storeId: "1233",
    storeName: "Poly Moly",
    city: "Bali",
    address: "Apart 30",
    ownerPhoneNumber: "09292929202",
    ownerName: "Ceon",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: false,
    supplierStatus: "Pending",
    actions: ["Edit", "Delete"],
  },
  {
    storeId: "1233",
    storeName: "Poly Moly",
    city: "Bali",
    address: "Apart 30",
    ownerPhoneNumber: "09292929202",
    ownerName: "Ceon",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: false,
    supplierStatus: "Pending",
    actions: ["Edit", "Delete"],
  },
  {
    storeId: "1233",
    storeName: "Poly Moly",
    city: "Bali",
    address: "Apart 30",
    ownerPhoneNumber: "09292929202",
    ownerName: "Ceon",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: false,
    supplierStatus: "Pending",
    actions: ["Edit", "Delete"],
  },
  {
    storeId: "1233",
    storeName: "Poly Moly",
    city: "Bali",
    address: "Apart 30",
    ownerPhoneNumber: "09292929202",
    ownerName: "Ceon",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: false,
    supplierStatus: "Pending",
    actions: ["Edit", "Delete"],
  },
];
